name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Install pipenv
      run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
    - name: Generate requirements.txt
      run: pipenv lock -r > requirements.txt
    - name: Install dependencies
      run: pip install -r requirements.txt
    - run: pip install -r requirements.txt
    - run: pytest --cov=capture --cov-fail-under=100
