name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: python -m pip install --upgrade pip
    - run: pip install pipenv
    - run: pipenv install --dev
    - name: Install CPU-only PyTorch
      run: pipenv run pip install torch --index-url https://download.pytorch.org/whl/cpu
    - run: pipenv run pytest --cov=capture --cov-fail-under=100
